-- =============================================================
-- GRUPO FLEX - KANBAN OPERACIONAL (SUPABASE/POSTGRES)
-- =============================================================

-- -------------------------------------------------------------
-- Tabela: profiles (Extensão da auth.users)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id           UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  email        TEXT NOT NULL UNIQUE,
  role         TEXT CHECK (role IN ('admin', 'user')) DEFAULT 'user',
  active       BOOLEAN DEFAULT TRUE,
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  updated_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------
-- Tabela: columns_kanban
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.columns_kanban (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  color        TEXT DEFAULT '#00897B',
  icon         TEXT DEFAULT 'label',
  position     INTEGER DEFAULT 0,
  category     TEXT DEFAULT 'cartao',
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.columns_kanban ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------
-- Tabela: cards
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cards (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  column_id           BIGINT REFERENCES public.columns_kanban(id) ON DELETE SET NULL,
  title               TEXT NOT NULL,
  description         TEXT,
  category            TEXT DEFAULT 'cartao',
  pos_request_type    TEXT, -- Envio, Retirada ou Reverso
  pos_reason          TEXT, -- Motivo para retirada ou reverso
  company_name        TEXT,
  remessa             TEXT,
  placa               TEXT, -- Primeira placa (compat. legado)
  card_number         TEXT, -- Número do cartão principal (compat. legado)
  extra_data          JSONB, -- Dados extras em JSONB para melhor performance
  client_name         TEXT,
  client_email        TEXT,
  cnpj                TEXT,
  address             JSONB, -- Endereço em JSONB
  tracking_code       TEXT,
  reverse_tracking_code TEXT,
  tracking_status     TEXT,
  tracking_updated_at TIMESTAMPTZ,
  deadline            DATE,
  deadline_met        INTEGER CHECK (deadline_met IN (0, 1)), -- 1=cumprido, 0=atrasado, NULL=aberto
  priority            TEXT DEFAULT 'media' CHECK (priority IN ('baixa', 'media', 'alta')),
  position            INTEGER DEFAULT 0,
  created_by          UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_from_email  BOOLEAN DEFAULT FALSE,
  is_archived         BOOLEAN DEFAULT FALSE,
  withdrawal_declaration TEXT,
  correios_prepost_id TEXT,
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cards ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------
-- Tabela: comments
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.comments (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id      BIGINT NOT NULL REFERENCES public.cards(id) ON DELETE CASCADE,
  user_id      UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  user_name    TEXT,
  content      TEXT NOT NULL,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------
-- Tabela: card_history
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.card_history (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_id      BIGINT NOT NULL REFERENCES public.cards(id) ON DELETE CASCADE,
  user_id      UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  user_name    TEXT,
  action       TEXT NOT NULL,
  old_col_name TEXT,
  new_col_name TEXT,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.card_history ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------
-- Módulos de Inventário
-- -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.pos_equipments (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model        TEXT NOT NULL,
  serial_number TEXT NOT NULL UNIQUE,
  chip_iccid   TEXT,
  status       TEXT DEFAULT 'Estoque',
  created_at   TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.pos_equipments ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.trackers (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model        TEXT,
  serial_number TEXT NOT NULL UNIQUE,
  chip_iccid   TEXT,
  status       TEXT DEFAULT 'Estoque',
  created_at   TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.trackers ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.sim_cards (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_number TEXT NOT NULL UNIQUE,
  iccid        TEXT NOT NULL UNIQUE,
  carrier      TEXT,
  status       TEXT DEFAULT 'Estoque',
  motivo       TEXT,
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);
ALTER TABLE public.sim_cards ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------
-- Tabelas de Automação
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.automation_rules (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  category     TEXT NOT NULL,
  trigger_event TEXT NOT NULL,
  trigger_config JSONB,
  is_active    BOOLEAN DEFAULT TRUE,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.automation_rules ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.automation_actions (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id      BIGINT NOT NULL REFERENCES public.automation_rules(id) ON DELETE CASCADE,
  action_type  TEXT NOT NULL,
  action_config JSONB,
  position     INTEGER DEFAULT 0
);
ALTER TABLE public.automation_actions ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------
-- DADOS INICIAIS
-- -------------------------------------------------------------
INSERT INTO public.columns_kanban (name, color, icon, position, category) VALUES
  ('Recebido',         '#00897B', 'inbox',        1, 'cartao'),
  ('Em Andamento',     '#00897B', 'settings',     2, 'cartao'),
  ('Aguardando Envio', '#00897B', 'schedule',     3, 'cartao'),
  ('Enviado',          '#00897B', 'send',         4, 'cartao'),
  ('Retornos',         '#E64A19', 'replay',       5, 'cartao'),
  ('Entregue',         '#2E7D32', 'check_circle', 6, 'cartao');

-- -------------------------------------------------------------
-- POLÍTICAS RLS BÁSICAS (Permitir tudo para autenticados para facilitar inicial)
-- -------------------------------------------------------------
-- Nota: Em produção, estas políticas devem ser mais restritivas.

CREATE POLICY "Allow all to authenticated" ON public.profiles FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to authenticated" ON public.columns_kanban FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to authenticated" ON public.cards FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to authenticated" ON public.comments FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to authenticated" ON public.card_history FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to authenticated" ON public.pos_equipments FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to authenticated" ON public.trackers FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to authenticated" ON public.sim_cards FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to authenticated" ON public.automation_rules FOR ALL TO authenticated USING (true);
CREATE POLICY "Allow all to authenticated" ON public.automation_actions FOR ALL TO authenticated USING (true);
